### ISSUE TITLE
can not download the pre-trained models

### ISSUE THREAD

**Issue by xixihawokao** [jaleedkhan/jSGG#2]
hi, the code you write is exactly what I need，when I run ”j_SGG.ipynb“  on colab than i get this：

# downloading pretrained models
import boto3
if os.path.isdir('upload_causal_motif_sgdet'):
    print("'jSGG/upload_causal_motif_sgdet' already exists")
else:
    #wget -O ucms.zip "https://onedrive.live.com/download?cid=22376FFAD72C4B64&resid=22376FFAD72C4B64%21781947&authkey=AF_EM-rkbMyT3gs"
    boto3.Session().resource('s3').Bucket('jaleed-bucket').download_file('upload_causal_motif_sgdet.zip','upload_causal_motif_sgdet.zip')
    !unzip upload_causal_motif_sgdet.zip -d upload_causal_motif_sgdet/
======================================================================================
---------------------------------------------------------------------------
NoCredentialsError                        Traceback (most recent call last)
[<ipython-input-10-78ee45f565ce>](https://localhost:8080/#) in <module>()
      5 else:
      6     #wget -O ucms.zip "https://onedrive.live.com/download?cid=22376FFAD72C4B64&resid=22376FFAD72C4B64%21781947&authkey=AF_EM-rkbMyT3gs"
----> 7     boto3.Session().resource('s3').Bucket('jaleed-bucket').download_file('upload_causal_motif_sgdet.zip','upload_causal_motif_sgdet.zip')
      8     get_ipython().system('unzip upload_causal_motif_sgdet.zip -d upload_causal_motif_sgdet/')

18 frames
[/usr/local/lib/python3.7/dist-packages/botocore/auth.py](https://localhost:8080/#) in add_auth(self, request)
    386     def add_auth(self, request):
    387         if self.credentials is None:
--> 388             raise NoCredentialsError()
    389         datetime_now = datetime.datetime.utcnow()
    390         request.context['timestamp'] = datetime_now.strftime(SIGV4_TIMESTAMP)

NoCredentialsError: Unable to locate credentials
======================================================================================
the source  seems unreachable ， how can i solve this？

**Comment by xixihawokao** [comment]
> 

i solve this problem by use "wget -O ucms.zip "https://onedrive.live.com/download?cid=22376FFAD72C4B64&resid=22376FFAD72C4B64%21781947&authkey=AF_EM-rkbMyT3gs",
===================================================================
another thing is that i wonder why i use chrome to open this link ,then it show me the link was broken,but i download this file by  this command

**Comment by jaleedkhan** [comment]
I'm glad the notebook is useful for you. I just verified the wget command is working and the link is not broken. I hope you were able to download the file.
