### ISSUE TITLE
NoCredentialsError

### ISSUE THREAD

**Issue by preeti-me** [jaleedkhan/jSGG#3]
NoCredentialsError                        Traceback (most recent call last)
[<ipython-input-84-4865901c3e2d>](https://localhost:8080/#) in <module>
      6 #f = fs.open(f'https://cs.stanford.edu/people/rak248/VG_100K/2370463.jpg')
      7 #f = fs.open(f's3://jaleed-bucket/vg/images/2316655.jpg')
----> 8 f = fs.open(f's3://jaleed-bucket/vg/images/2317213.jpg')
      9 image = Image.open(f)
     10 pretrained_model_path = 'upload_causal_motif_sgdet/'

20 frames
[/usr/local/lib/python3.7/dist-packages/botocore/auth.py](https://localhost:8080/#) in add_auth(self, request)
    405     def add_auth(self, request):
    406         if self.credentials is None:
--> 407             raise NoCredentialsError()
    408         datetime_now = datetime.datetime.utcnow()
    409         request.context['timestamp'] = datetime_now.strftime(SIGV4_TIMESTAMP)

NoCredentialsError: Unable to locate credentials

**Comment by jaleedkhan** [comment]
Hi @preeti-me. Can you check the paths of variables 'f' and 'pretrained_model_path' - they should be paths on your local machine to a test image and the pre-trained network.
